### ISSUE TITLE
Operation Not Permitted

### ISSUE THREAD

**Issue by ghires** [TrafeX/docker-php-nginx#105]
I tried to run the container on a Raspberry Pi 4, but receive an "Operation not permitted." It seems related to python?

root@pi-02:/docker/nginx# docker run -p 49154:80 trafex/php-nginx
Unable to find image 'trafex/php-nginx:latest' locally
latest: Pulling from trafex/php-nginx
c6556b3b6858: Pull complete 
59aa6169e2f0: Pull complete 
c8a6ebd7429e: Pull complete 
430f82032b19: Pull complete 
857be4a76044: Pull complete 
adb309884695: Pull complete 
8e3e43cef476: Pull complete 
eeae13862d71: Pull complete 
cf9f1bad6ea1: Pull complete 
da00d3543b8a: Pull complete 
Digest: sha256:36899261c28e5c96503a3d97303acfe179f2ba91b9ae1b18eeda1387db1a94cf
Status: Downloaded newer image for trafex/php-nginx:latest
Traceback (most recent call last):
  File "/usr/bin/supervisord", line 33, in <module>
    sys.exit(load_entry_point('supervisor==4.2.4', 'console_scripts', 'supervisord')())
  File "/usr/bin/supervisord", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/supervisor/supervisord.py", line 41, in <module>
    from supervisor.options import ServerOptions
  File "/usr/lib/python3.10/site-packages/supervisor/options.py", line 13, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 77, in <module>
    __import__('packaging.specifiers')
  File "/usr/lib/python3.10/site-packages/packaging/specifiers.py", line 24, in <module>
    from .utils import canonicalize_version
  File "/usr/lib/python3.10/site-packages/packaging/utils.py", line 8, in <module>
    from .tags import Tag, parse_tag
  File "/usr/lib/python3.10/site-packages/packaging/tags.py", line 5, in <module>
    import logging
  File "/usr/lib/python3.10/logging/__init__.py", line 57, in <module>
    _startTime = time.time()
PermissionError: [Errno 1] Operation not permitted

Thank you!

**Comment by TrafeX** [comment]
Hi @ghires ,

I'm not sure what's causing this. When I run the exact same command on my Raspberry Pi 4 it just works.
I do see other people with comparable issues, seems like they reinstalled Docker; https://github.com/freqtrade/freqtrade/issues/6183
You could try that as well.

**Comment by b1ek** [comment]
Are you sure that you are running as root? Type `whoami` in the terminal to check the user

**Comment by b1ek** [comment]
To open docker shell as root, use `docker exec -it --user root your-cont-name sh`

**Comment by TrafeX** [comment]
Hi @ghires,

I'm closing this issue due to inactivity, let me know if you still experience issues!
